/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Tido": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
