import '@mantine/core/styles.css'
import type { Metadata } from 'next'
import './globals.css'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <MantineProvider>
        <body>{children}</body>
      </MantineProvider>
    </html>
  )
}
